repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.100.0"
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.20.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--config", "./.terraform-docs.yaml", "--recursive", "--output-file", "README.md", "./"]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.471'
    hooks:
      - id: checkov
        verbose: false
