repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.92.1"
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--config", "./.terraform-docs.yaml", "--recursive", "--output-file", "README.md", "./"]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.219'
    hooks:
      - id: checkov
        language_version: python3.11
        verbose: false
